### ISSUE TITLE
Always find transactions via our nodes

### ISSUE THREAD

**Issue by jserv** [BiiLabs/alfred.biilabs.io#8]
At present, the example about finding transactions refers to `thetangle.org`, which is confusing. Instead, we have to specify the nodes we maintain for Alfred APIs.

**Comment by jserv** [comment]
No more `tangle.biilabs.io:5566`. Use `https` instead.

**Comment by ender503** [comment]
The `https://tangle.biilabs.io` is used for IRI load balancer.
And `https://tangle-accel.biilabs.io` is used for the tangle-accelerator load balancer.

https://github.com/BiiLabs/engineering/blob/master/docs/servers.md
